ramblers:
  url:  https://www.ramblers.org.uk
  walkDescriptionPrefix: Age range 20s-40s
  groupCode: KT50
  listWalksPath: api/lbs/walks?groups=KT50
meetup:
  url: https://www.meetup.com
  apiUrl: https://api.meetup.com
  group: Kent-Ramblers
mongo:
  dbUrl:  https://api.mlab.com/api/1/databases
server:
  listenPort: 5000
  distFolder: dist/ng-ekwg
  uploadDir:  /tmp/ekwgFiles
  staticUrl:  /
  cookieSecret: ekwg
aws:
  region: eu-west-1
  domain: amazonaws.com
